<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Neoan;
use Neoan3\Model\CategoryModel;
use Neoan3\Apps\Db;

class Categories extends Neoan {
    function getCategories($params){
        return CategoryModel::listAll();
    }

    function postCategories($obj){
        $jwt = Stateless::restrict('user');
        Db::ask('category',['name'=>$obj['name']]);
        return ['request'=>'sent'];
    }

}
