<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Tutoring extends Unicore
{
    function init()
    {
        $this->uni('neoan3')
            ->addHead('title', 'Learn web development')
            ->hook('footer', 'header')
            ->hook('main', 'tutoring')
            ->output();
    }

}
