<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Article extends Unicore {
    function init(){
        $this->uni('neoan')->hook('main','article')->output();
    }

}
