<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use BluaBlue\Client;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan3;

class Blog extends Unicore
{
    private $view = 'blog';
    private $articles = [];
    function init()
    {
        $this->uni('neoan3')
             ->hook('header', 'header')
            ->callback($this, 'loadContext')
             ->hook('main', $this->view, ['articles'=>$this->articles])
             ->output();
    }
    function loadContext(Neoan3 $uni){
        $credentials = getCredentials()['neoan_us_blua_blue'];
        $client = new Client($credentials['userName'], $credentials['password']);
        $articles = $client->getArticleList(0,300,$credentials['userName']);
        // only published
        foreach ($articles as $article){
            if($article['publish_date']){
                $article['has_image'] = false;
                if($article['image_id']){
                    $article['has_image'] = true;
                }
                $this->articles[] = $article;
            }
        }
    }
}
