<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Neoan;
use Neoan3\Model\UserModel;

class Login extends Neoan {

    function postLogin($credentials){
        $user = UserModel::find(['user_name'=>$credentials['username']]);
    }

}
