<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Neoan;

class Login extends Neoan {
    function getLogin($obj){
        
    }

    function postLogin($obj){
        
    }

}
