<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Register extends Unicore {
    function init() {
        $this->uni('neoan')
             ->includeElement('register')
             ->hook('main', 'register')
             ->output();
    }

}
