<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;

class Register extends Unicore {
    private $vueElements = ['register'];
    function init() {

        $this->uni('neoan')
             ->callback($this,'vueComponents')
             ->hook('main', 'register')
             ->output();
    }

    /**
     * @param Neoan $uni
     */
    function vueComponents($uni){
        foreach($this->vueElements as $vueElement){
            $uni->vueComponent($vueElement);
        }

    }


}
