<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

/**
 * Class Portfolio
 * @package Neoan3\Components
 */

class Portfolio extends Unicore{
    /**
     * Route: portfolio
     */
    function init(): void
    {
        $this
            ->uni('Neoan3')
            ->hook('header', 'header')
            ->hook('main', 'portfolio')
            ->output();
    }
}