<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\DbException;
use Neoan3\Frame\Neoan;
use Neoan3\Model\ArticleModel;

class Search extends Neoan {
    function getSearch($obj){
        try{
            $found = [];
            $hits = Db::ask('/search',['text'=>$obj['q']]);
            foreach($hits as $hit){
                $found[] = ArticleModel::byId($hit['id']);
            }
            return $found;
        } catch(DbException $e){
            return [];
        }

    }


}
