<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Core\Serve;

class Voicer extends Serve {
    function constants() {
        return [
          'js'=>[
              ['src'=>'//cdnjs.cloudflare.com/ajax/libs/annyang/2.6.0/annyang.min.js']
          ]
        ];
    }
}
