<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Podcast extends Unicore
{
    function init()
    {
        $this->uni('neoan3')
             ->hook('header', 'header')
             ->includeJs(base . '/component/home/home.ctrl.js')
             ->hook('main', 'podcast')
             ->output();
    }

}
