<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Session;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;

class Profile extends Unicore {
    function init() {
        $this->uni('neoan')
             ->callback($this, 'secure')
             ->callback($this, 'components')
             ->includeElement('profile')
             ->hook('main', 'profile')
             ->output();
    }

    /**
     * @param Neoan $frame
     */
    function components($frame) {
        $frame->vueComponent('articleList');
    }

    function secure($uni) {
        Session::restricted();
    }

}
