<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Apps\Db;
use Neoan3\Apps\Cache;
use Neoan3\Apps\DbException;
use Neoan3\Apps\Session;
use Neoan3\Apps\Stateless;
use Neoan3\Core\Serve;

class Neoan extends Serve {
    private $developmentMode = true;
    protected $currentAuth = false;
    function __construct() {
        if(!$this->developmentMode){
            Cache::setCaching('+2 hours');
        }
        try{
            Db::setEnvironment(['name'=>'neoan_us','assumes_uuid'=>true]);
        } catch (DbException $e){
            echo "Warning: Database connection failed.";
        }
        // JWT/Stateless auth
        Stateless::setSecret('NiemalsGenugGeld');

        // Hybrid: construct session
        new Session();
        parent::__construct();


        $this->includeElement('header');
        $this->hook('header','header');
        $this->hook('footer','footer');

    }
    function vueComponent($element,$params=[]){
        $params['base'] = base;
        $path = path.'/component/'.$element.'/'.$element.'.ce.';
        if(file_exists($path.$this->viewExt)){
            $this->footer .= '<template id="'.$element.'">'.
                             $this->fileContent($path.$this->viewExt,$params).
                             '</template>';
        }
        if(file_exists($path.'js')){
            $this->js .= $this->fileContent($path.'js',$params);
        }

        return $this;
    }
    function restrict($scope){
        $this->currentAuth = Stateless::restrict($scope);
        return $this;
    }

    function output($params = []) {
        parent::output($params);
        if(!$this->developmentMode){
            Cache::write();
        }
    }

    function constants() {
        return [
            'base'=>[base],
            'link'=>[
                [
                    'sizes'=>'32x32',
                    'type'=>'image/png',
                    'rel'=>'icon',
                    'href'=>'asset/neoan-favicon.png'
                ]
            ],
            'meta'=>[
                ['name'=>'viewport','content'=>'width=device-width, initial-scale=1']
            ],
            'js'=>[
                ['src'=> 'https://use.fontawesome.com/releases/v5.3.1/js/all.js'],
                ['src'=> base.'asset/tinymce/js/tinymce/tinymce.min.js'],
                ['src'=> base.'node_modules/vue/dist/vue.js'],
                ['src'=> base.'node_modules/axios/dist/axios.min.js'],
                ['src'=> base.'node_modules/lodash/lodash.min.js'],
                ['src'=> path.'/frame/neoan/axios-wrapper.js','data'=>['base'=>base]],
            ],
            'stylesheet'=>[
                ''.base.'frame/neoan/main.css'
            ]
        ];
    }
}
