<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Core\Serve;

class Neoan extends Serve {
    function __construct() {

        parent::__construct();
        $this->includeElement('header');
        $this->hook('header','header');
        $this->hook('footer','footer');
    }

    function constants() {
        return [
            'base'=>[base],
            'link'=>[
                [
                    'sizes'=>'32x32',
                    'type'=>'image/png',
                    'rel'=>'icon',
                    'href'=>'asset/neoan-favicon.png'
                ]
            ],
            'meta'=>[
                ['name'=>'viewport','content'=>'width=device-width, initial-scale=1']
            ],
            'stylesheet'=>[
                ''.base.'node_modules/bulma/css/bulma.min.css',
                ''.base.'frame/neoan/style.css',
            ]
        ];
    }
}
