<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Db;

class ArticleModel extends IndexModel {
    static function byId($id){
        $tables = [];
        $article = Db::easy('article.* #article.insert_date:inserted',['id'=>'$'.$id]);
        foreach($tables as $table){
            $article[$table] = Db::easy($table.'.*',['article_id'=>'$'.$id,'^delete_date']);
        }
    }

    static function find($condition){
        
    }

}
