<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;


class NewPost extends Unicore {
    function init() {
        $this->uni('neoan')->includeJs('asset/tinymce/js/tinymce/tinymce.min.js')
             ->hook('main', 'newPost')
             ->output();
    }

}
