<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Db;

class CategoryModel extends IndexModel {
    static function byId($id){
        return parent::first(Db::easy('category.*',['id'=>'$'.$id]));
    }
    static function listAll(){
        $categories = [];
        foreach (Db::easy('category.id',['^delete_date']) as $category){
            $categories[] = self::byId($category['id']);
        }
        return $categories;
    }

    static function find($condition){
        
    }

}
