<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Voice extends Unicore {
    function init(){
        $this->uni('voicer')->hook('main','voice')->output();
    }

}
